# C'est le nom de votre projet.
name: 'job_offers_dbt'
version: '1.0.0'
config-version: 2

# Ce paramètre indique à dbt quel "profil" utiliser pour ce projet.
profile: 'job_offers_dbt'

# Ces configurations indiquent à dbt où chercher les différents types de fichiers.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # dossier qui stockera le SQL compilé et les artefacts
clean-targets:         # dossiers à supprimer par `dbt clean`
  - "target"
  - "dbt_packages"

# Configuration des modèles
# Ici, on dit à dbt comment matérialiser les modèles de dossiers spécifiques.
models:
  # Cette clé DOIT correspondre au 'name' de votre projet défini ci-dessus.
  job_offers_dbt:
    # Cette configuration s'applique à tous les modèles dans le sous-dossier 'staging'.
    staging:
      +materialized: view
    intermediate:
      +materialized: view # Intermediate models are usually views
    marts:
      +materialized: table # Final models for BI tools should be tables