version: 2

sources:
  - name: public
    schema: public
    tables:
      - name: raw_jobs
      - name: raw_companies
      - name: user_configs
        description: "Stores search configurations for superusers, including skill keywords."
      